# Generated by Django 3.2.5 on 2022-07-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220729_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.CharField(choices=[('DJ', 'Django'), ('Py', 'Python'), ('FL', 'Flask'), ('Ru', 'Rust'), ('ML', 'Machine Learning'), ('PB', 'Publications')], default='Py', max_length=2),
        ),
    ]
